# Generated by Django 6.0.7 on 2026-08-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System administrator'), ('mapping_admin', 'Mapping administrator'), ('faculty', 'Faculty'), ('learner', 'Learner')], default='learner', max_length=20),
        ),
    ]
