# Generated by Django 6.0.7 on 2026-08-03 02:01

import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIGradingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_name', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('output_schema', models.JSONField()),
                ('temperature', models.DecimalField(decimal_places=2, default=0.1, max_digits=3)),
                ('model_provider', models.CharField(default='openai', max_length=50)),
                ('model_name', models.CharField(default='configure-in-environment', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'ai_grading_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GradingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('grading_type', models.CharField(choices=[('rules_only', 'Rules only'), ('automated_tests', 'Automated tests'), ('ai_rubric', 'AI rubric'), ('hybrid', 'Hybrid'), ('manual', 'Manual')], default='hybrid', max_length=30)),
                ('structural_check_enabled', models.BooleanField(default=True)),
                ('automated_testing_enabled', models.BooleanField(default=False)),
                ('rag_enabled', models.BooleanField(default=True)),
                ('ai_grading_enabled', models.BooleanField(default=True)),
                ('manual_review_required', models.BooleanField(default=True)),
                ('confidence_review_threshold', models.DecimalField(decimal_places=3, default=0.7, max_digits=4)),
                ('version', models.PositiveIntegerField(default=1)),
                ('configuration', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'grading_configuration',
                'ordering': ('code',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rag_chunk',
                'ordering': ('rag_source', 'chunk_index'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RagSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('assignment_document', 'Assignment document'), ('rubric', 'Rubric'), ('model_answer', 'Model answer'), ('lecture_note', 'Lecture note'), ('policy', 'Policy'), ('example', 'Example')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_uri', models.TextField(blank=True, null=True)),
                ('source_text', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('ingestion_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rag_source',
                'ordering': ('assignment_level', 'title'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricBand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('band_code', models.CharField(choices=[('failed', 'Failed'), ('foundation', 'Foundation'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=30)),
                ('display_name', models.CharField(max_length=100)),
                ('minimum_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descriptor', models.TextField()),
                ('sequence', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'rubric_band',
                'ordering': ('rubric_criterion', 'sequence'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('maximum_score', models.DecimalField(decimal_places=2, max_digits=7)),
                ('sequence', models.PositiveIntegerField()),
                ('ai_gradable', models.BooleanField(default=True)),
                ('deterministic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'rubric_criterion',
                'ordering': ('assignment_level', 'sequence'),
                'managed': False,
            },
        ),
    ]
