# Generated by Django 6.0.7 on 2026-08-11 07:16

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradingConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("grading_config_code", models.CharField(max_length=100, unique=True)),
                ("grading_config_name", models.CharField(max_length=255)),
                (
                    "grading_type",
                    models.CharField(
                        choices=[
                            ("rules_only", "Rules only"),
                            ("automated_tests", "Automated tests"),
                            ("ai_rubric", "AI rubric"),
                            ("hybrid", "Hybrid"),
                            ("manual", "Manual"),
                        ],
                        default="hybrid",
                        max_length=30,
                    ),
                ),
                ("structural_check_enabled", models.BooleanField(default=True)),
                ("automated_testing_enabled", models.BooleanField(default=False)),
                ("rag_enabled", models.BooleanField(default=True)),
                ("ai_grading_enabled", models.BooleanField(default=True)),
                ("manual_review_required", models.BooleanField(default=True)),
                (
                    "confidence_review_threshold",
                    models.DecimalField(decimal_places=3, default=0.7, max_digits=4),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("configuration", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("grading_config_code",),
            },
        ),
        migrations.CreateModel(
            name="AIGradingProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("profile_name", models.CharField(max_length=255)),
                ("system_prompt", models.TextField()),
                ("output_schema", models.JSONField()),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
                ),
                ("model_provider", models.CharField(default="openai", max_length=50)),
                (
                    "model_name",
                    models.CharField(
                        default="configure-in-environment", max_length=100
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_level",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_grading_profile",
                        to="courses.assignmentlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractedEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("image", "Image"),
                            ("table", "Table"),
                            ("metadata", "Metadata"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_text", models.TextField(blank=True)),
                ("file_path", models.CharField(blank=True, max_length=1024)),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        db_column="submission_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extracted_evidence",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "extracted_evidence",
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("map_tasks_criteria", "Map tasks to criteria"),
                            ("map_evidence_tasks", "Map evidence to tasks"),
                            ("final_assessment", "Final assessment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("prompt_text", models.TextField()),
                ("prompt_payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        db_column="submission_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prompts",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "prompt",
            },
        ),
        migrations.CreateModel(
            name="RagSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("assignment_document", "Assignment document"),
                            ("rubric", "Rubric"),
                            ("model_answer", "Model answer"),
                            ("lecture_note", "Lecture note"),
                            ("policy", "Policy"),
                            ("example", "Example"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "source_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("storage_uri", models.TextField(blank=True, null=True)),
                ("source_text", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "ingestion_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rag_sources",
                        to="courses.assignmentlevel",
                    ),
                ),
            ],
            options={
                "ordering": ("assignment_level", "title"),
            },
        ),
        migrations.CreateModel(
            name="RagChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("token_count", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rag_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="grading.ragsource",
                    ),
                ),
            ],
            options={
                "ordering": ("rag_source", "chunk_index"),
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("response_payload", models.JSONField(default=dict)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        db_column="prompt_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="grading.prompt",
                    ),
                ),
            ],
            options={
                "db_table": "response",
            },
        ),
        migrations.CreateModel(
            name="RubricCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criterion_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("maximum_score", models.DecimalField(decimal_places=2, max_digits=7)),
                ("sequence", models.PositiveIntegerField()),
                ("ai_gradable", models.BooleanField(default=True)),
                ("deterministic", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rubric_criteria",
                        to="courses.assignmentlevel",
                    ),
                ),
            ],
            options={
                "ordering": ("assignment_level", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="RubricBand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "band_code",
                    models.CharField(
                        choices=[
                            ("failed", "Failed"),
                            ("foundation", "Foundation"),
                            ("proficient", "Proficient"),
                            ("expert", "Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                (
                    "minimum_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "maximum_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("descriptor", models.TextField()),
                ("sequence", models.PositiveIntegerField()),
                (
                    "rubric_criterion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="grading.rubriccriterion",
                    ),
                ),
            ],
            options={
                "ordering": ("rubric_criterion", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="CriterionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("awarded_marks", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "achievement_band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("failed", "Failed"),
                            ("foundation", "Foundation"),
                            ("proficient", "Proficient"),
                            ("expert", "Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        blank=True,
                        db_column="submission_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_results",
                        to="submissions.learnersubmission",
                    ),
                ),
                (
                    "rubric_criterion",
                    models.ForeignKey(
                        blank=True,
                        db_column="rubric_criterion_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_results",
                        to="grading.rubriccriterion",
                    ),
                ),
            ],
            options={
                "db_table": "criterion_result",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="assignment_level_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_tasks",
                        to="courses.assignmentlevel",
                    ),
                ),
            ],
            options={
                "db_table": "task",
                "ordering": ("assignment_level", "sequence"),
            },
        ),
        migrations.CreateModel(
            name="TaskCriteriaMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "inferred_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("ai_explanation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_level",
                    models.ForeignKey(
                        blank=True,
                        db_column="assignment_level_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_criteria_mappings",
                        to="courses.assignmentlevel",
                    ),
                ),
                (
                    "rubric_criterion",
                    models.ForeignKey(
                        blank=True,
                        db_column="rubric_criterion_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_mappings",
                        to="grading.rubriccriterion",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        db_column="task_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria_mappings",
                        to="grading.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_criteria_mapping",
            },
        ),
        migrations.CreateModel(
            name="TaskCriterionWeight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight_percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "band",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("failed", "Failed"),
                            ("foundation", "Foundation"),
                            ("proficient", "Proficient"),
                            ("expert", "Expert"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rubric_criterion",
                    models.ForeignKey(
                        blank=True,
                        db_column="rubric_criterion_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_weights",
                        to="grading.rubriccriterion",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        db_column="task_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_weights",
                        to="grading.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_criterion_weight",
            },
        ),
        migrations.CreateModel(
            name="TaskEvidenceMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mapping_role",
                    models.CharField(
                        choices=[("primary", "Primary"), ("supporting", "Supporting")],
                        default="supporting",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "evidence",
                    models.ForeignKey(
                        blank=True,
                        db_column="evidence_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_maps",
                        to="grading.extractedevidence",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        db_column="task_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_maps",
                        to="grading.task",
                    ),
                ),
            ],
            options={
                "db_table": "task_evidence_map",
            },
        ),
    ]
