# Generated by Django 6.0.7 on 2026-08-11 22:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTaskMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(max_length=100)),
                ("task_description", models.TextField(blank=True)),
                ("mapped_page_numbers", models.JSONField(default=list)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
                ),
                ("justification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_mappings",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_task_mapping",
                "unique_together": {("submission", "task_id")},
            },
        ),
    ]
