# Generated by Django 6.0.7 on 2026-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubriccriterion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
