# Generated by Django 6.0.7 on 2026-08-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gradingconfiguration",
            options={"ordering": ("grading_config_code",)},
        ),
        migrations.RenameField(
            model_name="gradingconfiguration",
            old_name="code",
            new_name="grading_config_code",
        ),
        migrations.RenameField(
            model_name="gradingconfiguration",
            old_name="name",
            new_name="grading_config_name",
        ),
    ]
