# Generated by Django 6.0.7 on 2026-08-13 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_moduleassignment_grading_configuration_and_more"),
        ("grading", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="taskcriteriamapping",
            unique_together={("task", "rubric_criterion")},
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="ai_explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_criteria_mappings",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="rubric_criterion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_mappings",
                to="grading.rubriccriterion",
            ),
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria_mappings",
                to="grading.task",
            ),
        ),
        migrations.RemoveField(
            model_name="taskcriteriamapping",
            name="created_at",
        ),
        migrations.CreateModel(
            name="SubmissionTaskMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(max_length=100)),
                ("task_description", models.TextField(blank=True)),
                ("mapped_page_numbers", models.JSONField(default=list)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=4),
                ),
                ("justification", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_mappings",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_task_mapping",
                "unique_together": {("submission", "task_id")},
            },
        ),
    ]
