# Generated by Django 6.0.7 on 2026-08-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Must be non-atomic so we can DELETE orphans and then ALTER TABLE
    # in separate DB transactions (PostgreSQL disallows ALTER on a table
    # that has pending trigger events within the same transaction).
    atomic = False

    dependencies = [
        ("courses", "0004_remove_assignmentlevel_assignment_and_more"),
        ("grading", "0001_initial"),
    ]

    operations = [
        # Step 1: Remove orphaned rows in grading tables whose assignment_level_id
        # no longer exists in courses_moduleassignment (old AssignmentLevel data).
        # Must delete CHILDREN before PARENTS to avoid FK constraint violations.
        #
        # Dependency chain:
        #   rubriccriterion  <- rubricband               (must delete rubricband first)
        #   rubriccriterion  <- task_criterion_weight
        #   rubriccriterion  <- task_criteria_mapping
        #   rubriccriterion  <- criterion_result
        #   task             <- task_criterion_weight     (must delete weights first)
        #   task             <- task_criteria_mapping     (must delete mappings first)
        #   task             <- task_evidence_map         (must delete evidence maps first)
        #
        # Table names:
        #   RubricCriterion    -> grading_rubriccriterion  (Django default)
        #   RubricBand         -> grading_rubricband       (Django default)
        #   RagSource          -> grading_ragsource        (Django default)
        #   AIGradingProfile   -> grading_aigradingprofile (Django default)
        #   Task               -> task                     (db_table = "task")
        #   TaskCriterionWeight-> task_criterion_weight    (db_table custom)
        #   TaskCriteriaMapping-> task_criteria_mapping    (db_table custom)
        #   TaskEvidenceMap    -> task_evidence_map        (db_table custom)
        #   CriterionResult    -> criterion_result         (db_table custom)
        migrations.RunSQL(
            sql="""
            -- Collect orphaned rubriccriterion IDs (criteria linked to old AssignmentLevel)
            -- Delete rubricband rows referencing those criteria first
            DELETE FROM grading_rubricband
            WHERE rubric_criterion_id IN (
                SELECT id FROM grading_rubriccriterion
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Collect orphaned task IDs (tasks linked to old AssignmentLevel)
            -- Delete task_criterion_weight rows referencing those tasks first
            DELETE FROM task_criterion_weight
            WHERE task_id IN (
                SELECT id FROM task
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Delete task_criteria_mapping rows referencing orphaned rubriccriterion
            DELETE FROM task_criteria_mapping
            WHERE rubric_criterion_id IN (
                SELECT id FROM grading_rubriccriterion
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Delete task_criteria_mapping rows referencing orphaned tasks
            DELETE FROM task_criteria_mapping
            WHERE task_id IN (
                SELECT id FROM task
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Delete task_evidence_map rows referencing orphaned tasks
            DELETE FROM task_evidence_map
            WHERE task_id IN (
                SELECT id FROM task
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Delete criterion_result rows referencing orphaned rubriccriterion
            DELETE FROM criterion_result
            WHERE rubric_criterion_id IN (
                SELECT id FROM grading_rubriccriterion
                WHERE assignment_level_id IS NOT NULL
                  AND assignment_level_id NOT IN (
                    SELECT id FROM courses_moduleassignment
                  )
            );

            -- Now safe to delete the parent orphaned rows
            DELETE FROM grading_rubriccriterion
            WHERE assignment_level_id IS NOT NULL
              AND assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );

            DELETE FROM grading_ragsource
            WHERE assignment_level_id IS NOT NULL
              AND assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );

            DELETE FROM grading_aigradingprofile
            WHERE assignment_level_id IS NOT NULL
              AND assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );

            DELETE FROM task
            WHERE assignment_level_id IS NOT NULL
              AND assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );

            DELETE FROM task_criteria_mapping
            WHERE assignment_level_id IS NOT NULL
              AND assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Now safe to alter the FKs to point at courses.moduleassignment
        migrations.AlterField(
            model_name="aigradingprofile",
            name="assignment_level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_grading_profile",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="ragsource",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_sources",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="rubriccriterion",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_criteria",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                db_column="assignment_level_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_tasks",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                db_column="assignment_level_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_criteria_mappings",
                to="courses.moduleassignment",
            ),
        ),
    ]
