# Generated by Django 6.0.7 on 2026-08-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractedevidence",
            options={"ordering": ("submission", "page_number", "created_at")},
        ),
        migrations.RemoveField(
            model_name="extractedevidence",
            name="evidence_type",
        ),
        migrations.RemoveField(
            model_name="extractedevidence",
            name="file_path",
        ),
        migrations.AddField(
            model_name="extractedevidence",
            name="image_url",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="extractedevidence",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="extractedevidence",
            name="content_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="extractedevidence",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                db_column="submission_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_evidences",
                to="submissions.learnersubmission",
            ),
        ),
    ]
