# Generated by Django 6.0.7 on 2026-08-05 22:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('awarded_marks', models.DecimalField(decimal_places=2, max_digits=8)),
                ('achievement_band', models.CharField(blank=True, choices=[('failed', 'Failed'), ('foundation', 'Foundation'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=30)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'criterion_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtractedEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('table', 'Table'), ('metadata', 'Metadata')], max_length=20)),
                ('content_text', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=1024)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'extracted_evidence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('map_tasks_criteria', 'Map tasks to criteria'), ('map_evidence_tasks', 'Map evidence to tasks'), ('final_assessment', 'Final assessment')], max_length=50)),
                ('prompt_text', models.TextField()),
                ('prompt_payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('response_payload', models.JSONField(default=dict)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_code', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task',
                'ordering': ('assignment_level', 'sequence'),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCriteriaMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inferred_weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ai_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_criteria_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskCriterionWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('band', models.CharField(blank=True, choices=[('failed', 'Failed'), ('foundation', 'Foundation'), ('proficient', 'Proficient'), ('expert', 'Expert')], max_length=30)),
            ],
            options={
                'db_table': 'task_criterion_weight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TaskEvidenceMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_role', models.CharField(choices=[('primary', 'Primary'), ('supporting', 'Supporting')], default='supporting', max_length=20)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'task_evidence_map',
                'managed': False,
            },
        ),
    ]
