# Generated by Django 6.0.7 on 2026-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedevidence",
            name="page_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
