# Generated by Django 6.0.7 on 2026-08-12 07:24

from django.db import migrations
from pgvector.django import VectorExtension

class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
    ]
