# Generated by Django 6.0.7 on 2026-08-12 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("grading", "0002_enable_vector_extension"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aigradingprofile",
            name="assignment_level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_grading_profile",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="ragsource",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_sources",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="rubriccriterion",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_criteria",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                db_column="assignment_level_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grading_tasks",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                db_column="assignment_level_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_criteria_mappings",
                to="courses.assignmentlevel",
            ),
        ),
    ]
