# Generated by Django 6.0.7 on 2026-08-10 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_remove_assignmentlevel_level_assign_active_idx_and_more"),
        ("grading", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ragchunk",
            name="chunk_source_idx_idx",
        ),
        migrations.RemoveIndex(
            model_name="ragsource",
            name="ragsource_level_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="rubricband",
            name="band_criterion_code_idx",
        ),
        migrations.RemoveIndex(
            model_name="rubriccriterion",
            name="criterion_level_seq_idx",
        ),
        migrations.AlterField(
            model_name="aigradingprofile",
            name="assignment_level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_grading_profile",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="ragchunk",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ragchunk",
            name="rag_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="grading.ragsource",
            ),
        ),
        migrations.AlterField(
            model_name="ragsource",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rag_sources",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="ragsource",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="rubricband",
            name="rubric_criterion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bands",
                to="grading.rubriccriterion",
            ),
        ),
        migrations.AlterField(
            model_name="rubriccriterion",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rubric_criteria",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="rubriccriterion",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelTable(
            name="aigradingprofile",
            table=None,
        ),
        migrations.AlterModelTable(
            name="gradingconfiguration",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ragchunk",
            table=None,
        ),
        migrations.AlterModelTable(
            name="ragsource",
            table=None,
        ),
        migrations.AlterModelTable(
            name="rubricband",
            table=None,
        ),
        migrations.AlterModelTable(
            name="rubriccriterion",
            table=None,
        ),
    ]
