# Generated by Django 6.0.7 on 2026-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0002_alter_aigradingprofile_assignment_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubricband",
            name="display_name",
            field=models.CharField(max_length=300),
        ),
    ]
