# Generated by Django 6.0.7 on 2026-08-13 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_moduleassignment_grading_configuration_and_more"),
        ("grading", "0002_alter_taskcriteriamapping_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskcriteriamapping",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_criteria_mappings",
                to="courses.moduleassignment",
            ),
        ),
    ]
