# Generated by Django 6.0.7 on 2026-08-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_alter_rubriccriterion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragchunk',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ragsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
