# Generated by Django 6.0.7 on 2026-09-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grading", "0003_alter_aigradingprofile_assignment_level_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="instructions",
            new_name="evidence_required",
        ),
    ]
