from django.urls import path

from .views import (
    AssignmentLevelDetailView,
    AssignmentLevelConfigurationLockView,
    AssignmentLevelListCreateView,
    CohortDeleteImpactView,
    CohortDetailView,
    CohortListCreateView,
    ModuleAssignmentListCreateView,
    ModuleAssignmentDeleteImpactView,
    ModuleAssignmentSafeDetailView,
    ModuleDeleteImpactView,
    ModuleDetailView,
    ModuleListCreateView,
    QualificationDeleteImpactView,
    QualificationDetailView,
    QualificationListCreateView,
)

urlpatterns = [
    path(
        "qualifications/",
        QualificationListCreateView.as_view(),
        name="qualification-list-create",
    ),
    path(
        "qualifications/<uuid:id>/",
        QualificationDetailView.as_view(),
        name="qualification-detail",
    ),
    path(
        "modules/",
        ModuleListCreateView.as_view(),
        name="module-list-create",
    ),
    path(
        "modules/<uuid:id>/",
        ModuleDetailView.as_view(),
        name="module-detail",
    ),
    path(
        "cohorts/",
        CohortListCreateView.as_view(),
        name="cohort-list-create",
    ),
    path(
        "cohorts/<uuid:id>/",
        CohortDetailView.as_view(),
        name="cohort-detail",
    ),
    path(
        "assignments/",
        ModuleAssignmentListCreateView.as_view(),
        name="assignment-list-create",
    ),
    path(
        "assignments/<uuid:id>/",
        ModuleAssignmentSafeDetailView.as_view(),
        name="assignment-detail",
    ),
    path(
        "assignments/<uuid:id>/delete-impact/",
        ModuleAssignmentDeleteImpactView.as_view(),
        name="assignment-delete-impact",
    ),
    path(
        "assignment-levels/",
        AssignmentLevelListCreateView.as_view(),
        name="assignment-level-list-create",
    ),
    path(
        "assignment-levels/<uuid:level_id>/edit-lock/",
        AssignmentLevelConfigurationLockView.as_view(),
        name="assignment-level-edit-lock",
    ),
    path(
        "assignment-levels/<uuid:id>/",
        AssignmentLevelDetailView.as_view(),
        name="assignment-level-detail",
    ),
    path(
        "qualifications/<uuid:id>/delete-impact/",
        QualificationDeleteImpactView.as_view(),
        name="qualification-delete-impact",
    ),
    path(
        "modules/<uuid:id>/delete-impact/",
        ModuleDeleteImpactView.as_view(),
        name="module-delete-impact",
    ),
    path(
        "cohorts/<uuid:id>/delete-impact/",
        CohortDeleteImpactView.as_view(),
        name="cohort-delete-impact",
    ),
]
