from django.urls import path

from .views import (
    AssignmentLevelDetailView,
    AssignmentLevelListCreateView,
    CohortDetailView,
    CohortListCreateView,
    ModuleAssignmentDetailView,
    ModuleAssignmentListCreateView,
    ModuleDetailView,
    ModuleListCreateView,
    QualificationDetailView,
    QualificationListCreateView,
)

urlpatterns = [
    path(
        "qualifications/",
        QualificationListCreateView.as_view(),
        name="qualification-list-create",
    ),
    path(
        "qualifications/<uuid:id>/",
        QualificationDetailView.as_view(),
        name="qualification-detail",
    ),
    path(
        "modules/",
        ModuleListCreateView.as_view(),
        name="module-list-create",
    ),
    path(
        "modules/<uuid:id>/",
        ModuleDetailView.as_view(),
        name="module-detail",
    ),
    path(
        "cohorts/",
        CohortListCreateView.as_view(),
        name="cohort-list-create",
    ),
    path(
        "cohorts/<uuid:id>/",
        CohortDetailView.as_view(),
        name="cohort-detail",
    ),
    path(
        "assignments/",
        ModuleAssignmentListCreateView.as_view(),
        name="assignment-list-create",
    ),
    path(
        "assignments/<uuid:id>/",
        ModuleAssignmentDetailView.as_view(),
        name="assignment-detail",
    ),
    path(
        "assignment-levels/",
        AssignmentLevelListCreateView.as_view(),
        name="assignment-level-list-create",
    ),
    path(
        "assignment-levels/<uuid:id>/",
        AssignmentLevelDetailView.as_view(),
        name="assignment-level-detail",
    ),
]
