# Generated by Django 6.0.7 on 2026-08-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_deployment_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_jwks_url",
            field=models.URLField(blank=True),
        ),
    ]
