# Generated by Django 6.0.7 on 2026-08-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def copy_assignment_from_level(apps, schema_editor):
    AssessmentMapping = apps.get_model(
        "lms",
        "AssessmentMapping",
    )

    for mapping in AssessmentMapping.objects.select_related(
        "assignment_level"
    ):
        mapping.assignment_id = (
            mapping.assignment_level.assignment_id
        )
        mapping.save(
            update_fields=["assignment"]
        )

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_add_indexes'),
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
    migrations.AddField(
        model_name="assessmentmapping",
        name="assignment",
        field=models.ForeignKey(
            blank=True,
            null=True,
            on_delete=django.db.models.deletion.PROTECT,
            related_name="assessment_mappings",
            to="courses.moduleassignment",
        ),
    ),

    migrations.RunPython(
        copy_assignment_from_level,
        migrations.RunPython.noop,
    ),

    migrations.RemoveField(
        model_name="assessmentmapping",
        name="assignment_level",
    ),

    migrations.AddConstraint(
        model_name="assessmentmapping",
        constraint=models.UniqueConstraint(
            fields=("cohort", "assignment"),
            name="unique_cohort_assignment_mapping",
        ),
    ),
]
