# Generated by Django 6.0.7 on 2026-08-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_assessmentmapping_lti_client_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_access_token_url",
            field=models.URLField(blank=True),
        ),
    ]
