# Generated by Django 6.0.7 on 2026-08-08 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_cohort_options_rename_code_cohort_cohort_code_and_more'),
        ('lms', '0002_remove_assessmentmapping_assignment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmapping',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_mappings', to='courses.moduleassignment'),
        ),
    ]
