# Generated by Django 6.0.7 on 2026-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_assessmentmapping_lti_access_token_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="final_mark_weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
