# Generated by Django 6.0.7 on 2026-08-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assessmentmapping",
            name="mapping_cohort_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="assessmentmapping",
            name="mapping_assign_active_idx",
        ),
    ]
