# Generated by Django 6.0.7 on 2026-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_assessmentmapping_final_mark_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
