# Generated by Django 6.0.7 on 2026-08-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_assessmentmapping_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_ags_lineitem_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assessmentmapping",
            name="lti_ags_lineitems_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
