# Generated by Django 6.0.7 on 2026-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0007_assessmentmapping_show_result_to_learner"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentmapping",
            name="require_faculty_approval",
            field=models.BooleanField(default=False),
        ),
    ]
