# Generated by Django 6.0.7 on 2026-08-03 02:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradingRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='queued', max_length=30)),
                ('structural_result', models.JSONField(default=dict)),
                ('automated_test_result', models.JSONField(default=dict)),
                ('retrieved_rag_context', models.JSONField(default=list)),
                ('ai_result', models.JSONField(default=dict)),
                ('final_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('maximum_score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('achieved_band', models.CharField(blank=True, max_length=30, null=True)),
                ('requires_manual_review', models.BooleanField(default=False)),
                ('review_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'grading_run',
                'ordering': ('-created_at',),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('learner_id', models.UUIDField()),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('submitted_file_uri', models.TextField()),
                ('original_filename', models.CharField(max_length=255)),
                ('detected_assignment_code', models.CharField(blank=True, max_length=50, null=True)),
                ('detected_level_code', models.CharField(blank=True, max_length=20, null=True)),
                ('mapping_status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('mismatch', 'Mismatch'), ('manual_review', 'Manual review')], default='pending', max_length=30)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('validating', 'Validating'), ('grading', 'Grading'), ('completed', 'Completed'), ('failed', 'Failed'), ('manual_review', 'Manual review')], default='uploaded', max_length=30)),
                ('grading_configuration_snapshot', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submission',
                'ordering': ('-submitted_at',),
                'managed': False,
            },
        ),
    ]
