# Generated by Django 6.0.7 on 2026-08-12 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnersubmission",
            name="assignment_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learner_submissions",
                to="courses.assignmentlevel",
            ),
        ),
        migrations.AlterField(
            model_name="submissioncontext",
            name="assignment_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_contexts_by_assignment",
                to="courses.assignmentlevel",
            ),
        ),
    ]
