# Generated by Django 6.0.7 on 2026-08-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionpage',
            options={'ordering': ['page_number']},
        ),
        migrations.RemoveConstraint(
            model_name='submissionpage',
            name='unique_submission_page_number',
        ),
        migrations.AlterUniqueTogether(
            name='submissionpage',
            unique_together={('submission', 'page_number')},
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissionpage',
            name='image_mime_type',
            field=models.CharField(default='image/webp', max_length=50),
        ),
        migrations.AlterField(
            model_name='submissionpage',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterModelTable(
            name='submissionpage',
            table=None,
        ),
        migrations.RemoveField(
            model_name='submissionpage',
            name='page_image',
        ),
    ]
