# Generated by Django 6.0.7 on 2026-08-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    # Must be non-atomic so we can DELETE orphans and then ALTER TABLE
    # in separate DB transactions (PostgreSQL disallows ALTER on a table
    # that has pending trigger events within the same transaction).
    atomic = False

    dependencies = [
        ("courses", "0004_remove_assignmentlevel_assignment_and_more"),
        ("submissions", "0001_initial"),
    ]

    operations = [
        # Step 1: Remove orphaned rows whose assignment_level_id no longer
        # exists in courses_moduleassignment (old AssignmentLevel data).
        # Note: LearnerSubmission uses db_table="learner_submission"
        #       SubmissionContext uses Django default "submissions_submissioncontext"
        migrations.RunSQL(
            sql="""
            DELETE FROM learner_submission
            WHERE assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );

            DELETE FROM submissions_submissioncontext
            WHERE assignment_level_id NOT IN (
                SELECT id FROM courses_moduleassignment
            );
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Step 2: Now safe to alter the FK to point at courses.moduleassignment
        migrations.AlterField(
            model_name="learnersubmission",
            name="assignment_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="learner_submissions",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="submissioncontext",
            name="assignment_level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submission_contexts",
                to="courses.moduleassignment",
            ),
        ),
    ]
