# Generated by Django 6.0.7 on 2026-08-03 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
        ('submissions', '0002_learnersubmission_submissioncontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncontext',
            name='assessment_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_contexts', to='lms.assessmentmapping'),
        ),
    ]
