# Generated by Django 6.0.7 on 2026-08-22 05:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0002_alter_learnersubmission_assignment_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionGradingAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("error", "Error"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                (
                    "grader_version",
                    models.CharField(default="submission_grader_v1", max_length=100),
                ),
                ("task_mapping_snapshot", models.JSONField(blank=True, default=dict)),
                ("raw_ai_response", models.JSONField(blank=True, default=dict)),
                ("criterion_evaluations", models.JSONField(blank=True, default=list)),
                ("scoring_snapshot", models.JSONField(blank=True, default=dict)),
                ("overall_summary", models.TextField(blank=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_audit",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_grading_audit",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SubmissionProcessLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cohort_code", models.CharField(db_index=True, max_length=100)),
                ("cohort_name", models.CharField(blank=True, max_length=255)),
                ("assignment_code", models.CharField(db_index=True, max_length=100)),
                ("assignment_title", models.CharField(blank=True, max_length=255)),
                (
                    "learner_email",
                    models.EmailField(blank=True, db_index=True, max_length=254),
                ),
                ("learner_username", models.CharField(blank=True, max_length=255)),
                ("attempt_number", models.PositiveIntegerField(db_index=True)),
                ("stage", models.CharField(db_index=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "event_code",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("message", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_logs",
                        to="submissions.learnersubmission",
                    ),
                ),
            ],
            options={
                "db_table": "submission_process_log",
                "ordering": ("created_at",),
                "indexes": [
                    models.Index(
                        fields=[
                            "cohort_code",
                            "assignment_code",
                            "learner_email",
                            "attempt_number",
                        ],
                        name="sublog_attempt_lookup",
                    ),
                    models.Index(
                        fields=["stage", "status", "created_at"],
                        name="sublog_stage_status",
                    ),
                ],
            },
        ),
    ]
