# Generated by Django 6.0.7 on 2026-08-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnersubmission',
            name='submission_track',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced')], default='basic', max_length=20),
        ),
    ]
