# Generated by Django 6.0.7 on 2026-08-08 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def copy_assignment_from_assignment_level(apps, schema_editor):
        SubmissionContext = apps.get_model(
            "submissions",
            "SubmissionContext",
        )
        LearnerSubmission = apps.get_model(
            "submissions",
            "LearnerSubmission",
        )

        for context in SubmissionContext.objects.select_related(
            "assignment_level",
        ):
            if context.assignment_level_id:
                context.assignment_id = (
                    context.assignment_level.assignment_id
                )
                context.save(update_fields=["assignment"])

        for submission in LearnerSubmission.objects.select_related(
            "assignment_level",
        ):
            if submission.assignment_level_id:
                submission.assignment_id = (
                    submission.assignment_level.assignment_id
                )
                submission.save(update_fields=["assignment"])


    dependencies = [
        ('courses', '0004_alter_cohort_options_rename_code_cohort_cohort_code_and_more'),
        ('submissions', '0003_create_missing_submissionpage_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnersubmission',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learner_submissions_by_assignment', to='courses.moduleassignment'),
        ),
        migrations.AddField(
            model_name='submissioncontext',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_contexts_by_assignment', to='courses.moduleassignment'),
        ),
        migrations.RunPython(
            copy_assignment_from_assignment_level,
            migrations.RunPython.noop,
        ),
    ]
