# Generated by Django 6.0.7 on 2026-09-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_submissiongradingaudit_submissionprocesslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnersubmission",
            name="submission_track",
            field=models.CharField(max_length=50),
        ),
    ]
