# Generated by Django 6.0.7 on 2026-08-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_learnersubmission_submission_track"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="learnersubmission",
            name="submission_learner_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="learnersubmission",
            name="submission_context_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="learnersubmission",
            name="submission_status_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="submissioncontext",
            name="subctx_learner_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="submissioncontext",
            name="subctx_cohort_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="submissionpage",
            name="page_submission_idx",
        ),
    ]
