# Generated by Django 6.0.7 on 2026-08-08 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_learnersubmission_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnersubmission',
            name='assignment_level',
        ),
        migrations.RemoveField(
            model_name='submissioncontext',
            name='assignment_level',
        ),
    ]
