# Generated by Django 6.0.7 on 2026-09-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0005_learnersubmission_faculty_approved_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnersubmission",
            name="requires_faculty_approval",
            field=models.BooleanField(default=False),
        ),
    ]
