# Generated by Django 6.0.7 on 2026-08-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0005_remove_learnersubmission_assignment_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnersubmission',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('manual_review', 'Manual review')], default='uploaded', max_length=30),
        ),
    ]
