# Generated by Django 6.0.7 on 2026-09-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0006_learnersubmission_requires_faculty_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learnersubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                    ("manual_review", "Manual review"),
                    ("cancelled", "Cancelled"),
                ],
                default="uploaded",
                max_length=30,
            ),
        ),
    ]
