from django.urls import path

from .views import (
    ExtractedEvidenceDetailView,
    ExtractedEvidenceListCreateView,
    GradingConfigurationDetailView,
    GradingConfigurationListCreateView,
    RubricBandDetailView,
    RubricBandListCreateView,
    RubricCriterionDetailView,
    RubricCriterionListCreateView,
    TaskCriteriaMappingDetailView,
    TaskCriteriaMappingListCreateView,
    TaskDetailView,
    TaskListCreateView,
    AssignmentLevelConfigurationCsvImportView,
)

urlpatterns = [
    path(
        "configurations/",
        GradingConfigurationListCreateView.as_view(),
        name="grading-configuration-list-create",
    ),
    path(
        "configurations/<uuid:id>/",
        GradingConfigurationDetailView.as_view(),
        name="grading-configuration-detail",
    ),
    path(
        "rubric-criteria/",
        RubricCriterionListCreateView.as_view(),
        name="rubric-criterion-list-create",
    ),
    path(
        "rubric-criteria/<uuid:id>/",
        RubricCriterionDetailView.as_view(),
        name="rubric-criterion-detail",
    ),
    path(
        "rubric-bands/",
        RubricBandListCreateView.as_view(),
        name="rubric-band-list-create",
    ),
    path(
        "rubric-bands/<uuid:id>/",
        RubricBandDetailView.as_view(),
        name="rubric-band-detail",
    ),
    path(
        "tasks/",
        TaskListCreateView.as_view(),
        name="task-list-create",
    ),
    path(
        "tasks/<uuid:id>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "task-criteria-mappings/",
        TaskCriteriaMappingListCreateView.as_view(),
        name="task-criteria-mapping-list-create",
    ),
    path(
        "task-criteria-mappings/<uuid:id>/",
        TaskCriteriaMappingDetailView.as_view(),
        name="task-criteria-mapping-detail",
    ),
    path(
        "extracted-evidence/",
        ExtractedEvidenceListCreateView.as_view(),
        name="extracted-evidence-list-create",
    ),
    path(
        "extracted-evidence/<uuid:id>/",
        ExtractedEvidenceDetailView.as_view(),
        name="extracted-evidence-detail",
    ),
    path(
        "assignment-levels/<uuid:assignment_level_id>/import-csv/",
        AssignmentLevelConfigurationCsvImportView.as_view(),
        name="assignment-level-configuration-import-csv",
    ),
]
