# Generated by Django 6.0.7 on 2026-08-11 18:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enrolment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("learner", "Learner"), ("instructor", "Instructor")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "enrolment",
                "ordering": ("module", "user"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("module_code", models.CharField(max_length=50)),
                ("module_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("module_code",),
            },
        ),
        migrations.CreateModel(
            name="ModuleAssignment",
            fields=[
                (
                    "level",
                    models.CharField(
                        choices=[("basic", "Basic"), ("advanced", "Advanced")],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assignment_code", models.CharField(max_length=50)),
                ("assignment_title", models.CharField(max_length=255)),
                ("skill_statement_code", models.CharField(max_length=50)),
                ("skill_statement", models.TextField()),
                ("objective", models.TextField(blank=True)),
                ("maximum_score", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "minimum_pass_score",
                    models.DecimalField(decimal_places=2, max_digits=7),
                ),
                ("is_summative", models.BooleanField(default=True)),
                ("contributes_to_final_mark", models.BooleanField(default=True)),
                (
                    "final_mark_weight",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("module", "level", "assignment_code"),
            },
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("qualification_code", models.CharField(max_length=50, unique=True)),
                ("qualification_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("qualification_code",),
            },
        ),
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cohort_name", models.CharField(max_length=255)),
                ("cohort_code", models.CharField(max_length=100, unique=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.ForeignKey(
                        db_column="module_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "db_table": "cohort",
                "ordering": ("cohort_code",),
            },
        ),
    ]
