# Generated by Django 6.0.7 on 2026-08-12 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentlevel",
            name="grading_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignment_levels",
                to="grading.gradingconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="module",
            field=models.ForeignKey(
                db_column="module_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohorts",
                to="courses.module",
            ),
        ),
        migrations.AddField(
            model_name="moduleassignment",
            name="grading_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_assignments",
                to="grading.gradingconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="moduleassignment",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="courses.module",
            ),
        ),
        migrations.AddField(
            model_name="assignmentlevel",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="courses.qualification",
            ),
        ),
    ]
