# Generated by Django 6.0.7 on 2026-08-06 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('grading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentlevel',
            name='grading_configuration',
            field=models.ForeignKey(db_column='grading_configuration_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignment_levels', to='grading.gradingconfiguration'),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrolment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='courses.module'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='courses.module'),
        ),
        migrations.AddField(
            model_name='moduleassignment',
            name='module',
            field=models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='courses.module'),
        ),
        migrations.AddField(
            model_name='assignmentlevel',
            name='assignment',
            field=models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='courses.moduleassignment'),
        ),
        migrations.AddField(
            model_name='module',
            name='qualification',
            field=models.ForeignKey(db_column='qualification_id', on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='courses.qualification'),
        ),
        migrations.AddConstraint(
            model_name='enrolment',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='unique_user_module_enrolment'),
        ),
    ]
