# Generated by Django 6.0.7 on 2026-08-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentlevel",
            name="level_code",
            field=models.CharField(
                choices=[("basic", "BASIC"), ("advanced", "ADVANCED")], max_length=20
            ),
        ),
    ]
