# Generated by Django 6.0.7 on 2026-08-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ("module_code",)},
        ),
        migrations.RenameField(
            model_name="module",
            old_name="code",
            new_name="module_code",
        ),
        migrations.RenameField(
            model_name="module",
            old_name="name",
            new_name="module_name",
        ),
    ]
