# Generated by Django 6.0.7 on 2026-08-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ('qualification_code',)},
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='code',
            new_name='qualification_code',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='name',
            new_name='qualification_name',
        ),
    ]
