# Generated by Django 6.0.7 on 2026-08-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_cohort'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'managed': False, 'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='enrolment',
            options={'managed': False, 'ordering': ('module', 'user')},
        ),
    ]
