# Generated by Django 6.0.7 on 2026-08-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentlevel",
            name="objective",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assignmentlevel",
            name="skill_statement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="assignmentlevel",
            name="skill_statement_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="objective",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="skill_statement",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="skill_statement_code",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
