# Generated by Django 6.0.7 on 2026-08-11 18:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleassignment",
            name="grading_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="module_assignments",
                to="grading.gradingconfiguration",
            ),
        ),
        migrations.CreateModel(
            name="AssignmentLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level_code",
                    models.CharField(
                        choices=[("basic", "BASIC"), ("advanced", "ADVANCED")],
                        max_length=20,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("instructions", models.TextField(blank=True)),
                ("tasks", models.JSONField(default=list)),
                ("deliverables", models.JSONField(default=list)),
                ("expected_outcome", models.TextField(blank=True)),
                (
                    "source_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "configuration_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("retired", "Retired"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="courses.moduleassignment",
                    ),
                ),
                (
                    "grading_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assignment_levels",
                        to="grading.gradingconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ("level_code",),
            },
        ),
    ]
