# Generated by Django 6.0.1 on 2026-08-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_cohort_options_alter_enrolment_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cohort',
            table='cohort',
        ),
        migrations.AlterModelTable(
            name='enrolment',
            table='enrolment',
        ),
    ]
