# Generated by Django 6.0.7 on 2026-08-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_assignmentlevel_objective_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentlevel",
            name="scenario",
            field=models.TextField(blank=True, default=""),
        ),
    ]
