# Generated by Django 6.0.7 on 2026-08-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_assignmentlevel_level_code"),
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignmentlevel",
            name="assignment",
        ),
        migrations.RemoveField(
            model_name="assignmentlevel",
            name="grading_configuration",
        ),
        migrations.AlterModelOptions(
            name="moduleassignment",
            options={"ordering": ("module", "level", "assignment_code")},
        ),
        migrations.RemoveField(
            model_name="moduleassignment",
            name="assignment_number",
        ),
        migrations.AddField(
            model_name="moduleassignment",
            name="grading_configuration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_levels",
                to="grading.gradingconfiguration",
            ),
        ),
        migrations.AddField(
            model_name="moduleassignment",
            name="level",
            field=models.CharField(
                choices=[("basic", "Basic"), ("advanced", "Advanced")],
                default="basic",
                max_length=20,
            ),
        ),
    ]
