# Generated by Django 6.0.7 on 2026-08-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_qualification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ('cohort_code',)},
        ),
        migrations.RenameField(
            model_name='cohort',
            old_name='code',
            new_name='cohort_code',
        ),
        migrations.RenameField(
            model_name='cohort',
            old_name='name',
            new_name='cohort_name',
        ),
    ]
