# Generated by Django 6.0.7 on 2026-08-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_remove_assignmentlevel_assignment_and_more"),
        ("grading", "0002_alter_aigradingprofile_assignment_level_and_more"),
        ("submissions", "0002_alter_learnersubmission_assignment_level_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AssignmentLevel",
        ),
    ]
