# Generated by Django 6.0.7 on 2026-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_assignmentlevel_scenario"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentlevel",
            options={"ordering": ("assignment", "sequence", "created_at")},
        ),
        migrations.AddField(
            model_name="assignmentlevel",
            name="sequence",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="assignmentlevel",
            name="level_code",
            field=models.CharField(max_length=50),
        ),
    ]
