# Generated by Django 6.0.7 on 2026-09-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_alter_assignmentlevel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentlevel",
            name="band_definitions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
