# Generated by Django 6.0.7 on 2026-08-10 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0005_alter_cohort_options_rename_code_cohort_cohort_code_and_more",
        ),
        ("grading", "0002_add_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="assignmentlevel",
            name="level_assign_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="cohort",
            name="cohort_module_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="module",
            name="module_qual_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="moduleassignment",
            name="assignment_module_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="qualification",
            name="qual_active_idx",
        ),
        migrations.AlterField(
            model_name="assignmentlevel",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                to="courses.moduleassignment",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentlevel",
            name="grading_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignment_levels",
                to="grading.gradingconfiguration",
            ),
        ),

        migrations.AlterField(
            model_name="module",
            name="qualification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modules",
                to="courses.qualification",
            ),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="courses.module",
            ),
        ),
        migrations.AlterModelTable(
            name="assignmentlevel",
            table=None,
        ),
        migrations.AlterModelTable(
            name="module",
            table=None,
        ),
        migrations.AlterModelTable(
            name="moduleassignment",
            table=None,
        ),
        migrations.AlterModelTable(
            name="qualification",
            table=None,
        ),
    ]
